spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/victdb
    username: postgres
    password: welcome
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      jadira.usertype.autoRegisterUserTypes: true
      generate-ddl: false
            
logging:
  level:
    org.springframework.security: DEBUG
    
server:
  port: 18081    
  